# Generated by Django 3.1.2 on 2020-12-18 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_onelesson_comment_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessons',
            name='class_lesson',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.PROTECT, to='app1.classes'),
        ),
    ]
