# Generated by Django 3.1.2 on 2020-12-18 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_lessons_class_lesson'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lessons',
            name='class_lesson',
        ),
    ]
