# Generated by Django 3.1.2 on 2020-12-18 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_remove_lessons_class_lesson'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grade',
            name='grade_date',
        ),
    ]
