# Generated by Django 3.1.2 on 2020-12-18 15:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_remove_grade_grade_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='grade_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
